/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SimpleList {
    'list': { first: string, last: string }[];
  }
}

declare global {


  interface HTMLSimpleListElement extends Components.SimpleList, HTMLStencilElement {}
  var HTMLSimpleListElement: {
    prototype: HTMLSimpleListElement;
    new (): HTMLSimpleListElement;
  };
  interface HTMLElementTagNameMap {
    'simple-list': HTMLSimpleListElement;
  }
}

declare namespace LocalJSX {
  interface SimpleList {
    'list'?: { first: string, last: string }[];
    'onVote'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'simple-list': SimpleList;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'simple-list': LocalJSX.SimpleList & JSXBase.HTMLAttributes<HTMLSimpleListElement>;
    }
  }
}


