/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SimpleList {
    'list': { first: string, last: string }[];
    'title': string;
  }
  interface SimpleLogger {
    'logSomething': (something: string) => Promise<void>;
  }
}

declare global {


  interface HTMLSimpleListElement extends Components.SimpleList, HTMLStencilElement {}
  var HTMLSimpleListElement: {
    prototype: HTMLSimpleListElement;
    new (): HTMLSimpleListElement;
  };

  interface HTMLSimpleLoggerElement extends Components.SimpleLogger, HTMLStencilElement {}
  var HTMLSimpleLoggerElement: {
    prototype: HTMLSimpleLoggerElement;
    new (): HTMLSimpleLoggerElement;
  };
  interface HTMLElementTagNameMap {
    'simple-list': HTMLSimpleListElement;
    'simple-logger': HTMLSimpleLoggerElement;
  }
}

declare namespace LocalJSX {
  interface SimpleList {
    'list'?: { first: string, last: string }[];
    'onVote'?: (event: CustomEvent<any>) => void;
    'title'?: string;
  }
  interface SimpleLogger {}

  interface IntrinsicElements {
    'simple-list': SimpleList;
    'simple-logger': SimpleLogger;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'simple-list': LocalJSX.SimpleList & JSXBase.HTMLAttributes<HTMLSimpleListElement>;
      'simple-logger': LocalJSX.SimpleLogger & JSXBase.HTMLAttributes<HTMLSimpleLoggerElement>;
    }
  }
}


